// WarpLocations.swift

import Foundation

struct WarpPoint {
    let warpID: String
    let xPercent: Double
    let yPercent: Double
}

let imageSizes: [String: CGSize] = [
    "Sandgem": CGSize(width: 600, height: 402),
    "Jubilife": CGSize(width: 793, height: 599),
    "Jubilife GTS": CGSize(width: 426, height: 260),
    "Route 204": CGSize(width: 290, height: 280),
    "Route 203": CGSize(width: 151, height: 153),
    "Oreburgh": CGSize(width: 1000, height: 740),
    "Oreburgh Gate": CGSize(width: 451, height: 331),
    "Floaroma": CGSize(width: 611, height: 440),
    "Floaroma Meadow": CGSize(width: 404, height: 295),
    "Eterna": CGSize(width: 627, height: 712),
    "Eterna Forest": CGSize(width: 458, height: 322),
    "Hearthome": CGSize(width: 1000, height: 788),
    "Solaceon": CGSize(width: 1000, height: 412),
    "Solaceon Ruins": CGSize(width: 584, height: 378),
    "Veilstone": CGSize(width: 1000, height: 788),
    "Dept Store": CGSize(width: 720, height: 560),
    "Pastoria": CGSize(width: 1000, height: 684),
    "Celestic": CGSize(width: 752, height: 468),
    "Canalave": CGSize(width: 624, height: 600),
    "Iron Island": CGSize(width: 1000, height: 468),
    "Snowpoint": CGSize(width: 606, height: 634),
    "Sunyshore": CGSize(width: 1000, height: 790),
    "Valor Lakefront": CGSize(width: 669, height: 708),
    "Route 209": CGSize(width: 365, height: 205),
    "Route 210": CGSize(width: 223, height: 327),
    "Route 211": CGSize(width: 332, height: 136),
    "Route 212": CGSize(width: 485, height: 359),
    "Route 213": CGSize(width: 418, height: 302),
    "Route 214": CGSize(width: 225, height: 258),
    "Route 215": CGSize(width: 128, height: 143),
    "Route 216": CGSize(width: 354, height: 156),
    "Route 217": CGSize(width: 328, height: 124),
    "Route 221": CGSize(width: 508, height: 217),
    "Route 222": CGSize(width: 408, height: 176),
    "Route 205": CGSize(width: 448, height: 292),
    "Route 206": CGSize(width: 434, height: 416),
    "Route 207": CGSize(width: 246, height: 215),
    "Route 208": CGSize(width: 412, height: 298),
    "Route 223": CGSize(width: 0, height: 0),
    "Route 226": CGSize(width: 274, height: 180),
    "Route 227": CGSize(width: 146, height: 139),
    "Stark Mountain": CGSize(width: 300, height: 245),
    "Route 228": CGSize(width: 370, height: 296),
    "Backlot Mansion": CGSize(width: 926, height: 229),
    "Jubilife TV": CGSize(width: 674, height: 475),
    "Poketch": CGSize(width: 373, height: 192),
    "TG Eterna": CGSize(width: 740, height: 389),
    "Old Chateau": CGSize(width: 614, height: 352),
    "Galactic HQ": CGSize(width: 1000, height: 766),
    "Acuity Lakefront": CGSize(width: 245, height: 193),
    "Verity Lakefront": CGSize(width: 270, height: 154),
    "Mt Coronet": CGSize(width: 903, height: 800),
    "Coronet Peak": CGSize(width: 599, height: 711),
    "Pokemon League": CGSize(width: 840, height: 328),
    "Victory Road": CGSize(width: 1000, height: 766),
    "Fight Area": CGSize(width: 611, height: 428),
    "Survival Area": CGSize(width: 590, height: 468),
    "Resort Area": CGSize(width: 752, height: 456),
    "Fuego Ironworks": CGSize(width: 512, height: 596),
    "Lake Verity": CGSize(width: 864, height: 648),
    "Lake Valor": CGSize(width: 864, height: 720),
    "Lake Acuity": CGSize(width: 752, height: 612),
    "Pokemon League Outside": CGSize(width: 496, height: 996),
    "Valley Windworks": CGSize(width: 512, height: 407),
]

let warpPoints: [String: [WarpPoint]] = [
    "Sandgem": [
        WarpPoint(warpID: "Sandgem_Centre_Entrance", xPercent: 0.455, yPercent: 0.40),
        WarpPoint(warpID: "Sandgem_Mart_Entrance", xPercent: 0.72, yPercent: 0.40),
        WarpPoint(warpID: "Sandgem_House_Left", xPercent: 0.19, yPercent: 0.74),
        WarpPoint(warpID: "Sandgem_House_Right", xPercent: 0.42, yPercent: 0.74),
        WarpPoint(warpID: "Sandgem_Centre_Exit", xPercent: 0.81, yPercent: 0.95),
        WarpPoint(warpID: "Sandgem_Centre_Left", xPercent: 0.71, yPercent: 0.91),
        WarpPoint(warpID: "Sandgem_Centre_Right", xPercent: 0.91, yPercent: 0.91),
    ],
    "Jubilife": [
        WarpPoint(warpID: "Jubilife_Centre_Entrance", xPercent: 0.80, yPercent: 0.64),
        WarpPoint(warpID: "Jubilife_Mart_Entrance", xPercent: 0.79, yPercent: 0.48),
        WarpPoint(warpID: "Jubilife_House_Bottom", xPercent: 0.61, yPercent: 0.82),
        WarpPoint(warpID: "Jubilife_Condo", xPercent: 0.80, yPercent: 0.31),
        WarpPoint(warpID: "Jubilife_TV_Entrance", xPercent: 0.56, yPercent: 0.25),
        WarpPoint(warpID: "Jubilife_Poketch_Left", xPercent: 0.21, yPercent: 0.25),
        WarpPoint(warpID: "Jubilife_Poketch_Right", xPercent: 0.27, yPercent: 0.25),
        WarpPoint(warpID: "Jublife_Gate_West", xPercent: 0.05, yPercent: 0.36),
        WarpPoint(warpID: "Jubilife_GTS_Entrance", xPercent: 0.33, yPercent: 0.66),
        WarpPoint(warpID: "Jubilife_GTS_House", xPercent: 0.20, yPercent: 0.84),
        WarpPoint(warpID: "Jubilife_Centre_Exit", xPercent: 0.86, yPercent: 0.97),
        WarpPoint(warpID: "Jubilife_Centre_Left", xPercent: 0.78, yPercent: 0.95),
        WarpPoint(warpID: "Jubilife_Centre_Right", xPercent: 0.94, yPercent: 0.95),
    ],
    "Jubilife GTS": [
        WarpPoint(warpID: "Jubilife_GTS_Warp_Red", xPercent: 0.74, yPercent: 0.30),
        WarpPoint(warpID: "Jubilife_GTS_Warp_Green", xPercent: 0.59, yPercent: 0.30),
        WarpPoint(warpID: "Jubilife_GTS_Exit", xPercent: 0.48, yPercent: 0.89),
    ],
    "Oreburgh": [
        WarpPoint(warpID: "Oreburgh_Centre_Entrance", xPercent: 0.76, yPercent: 0.33),
        WarpPoint(warpID: "Oreburgh_Mart_Entrance", xPercent: 0.47, yPercent: 0.17),
        WarpPoint(warpID: "Oreburgh_Gym_Entrance", xPercent: 0.42, yPercent: 0.34),
        WarpPoint(warpID: "Oreburgh_Mine_Entrance", xPercent: 0.74, yPercent: 0.94),
        WarpPoint(warpID: "Oreburgh_Museum_Entrance", xPercent: 0.79, yPercent: 0.18),
        WarpPoint(warpID: "Oreburgh_House_Middle", xPercent: 0.60, yPercent: 0.26),
        WarpPoint(warpID: "Oreburgh_Gym_House", xPercent: 0.28, yPercent: 0.34),
        WarpPoint(warpID: "Oreburgh_Mine_House", xPercent: 0.82, yPercent: 0.61),
        WarpPoint(warpID: "Oreburgh_Museum_House", xPercent: 0.91, yPercent: 0.44),
        WarpPoint(warpID: "Oreburgh_Condo_Left", xPercent: 0.25, yPercent: 0.17),
        WarpPoint(warpID: "Oreburgh_Condo_Right", xPercent: 0.36, yPercent: 0.17),
        WarpPoint(warpID: "Oreburgh_Cave_West", xPercent: 0.05, yPercent: 0.18),
        WarpPoint(warpID: "Oreburgh_Centre_Exit", xPercent: 0.38, yPercent: 0.69),
        WarpPoint(warpID: "Oreburgh_Centre_Left", xPercent: 0.32, yPercent: 0.66),
        WarpPoint(warpID: "Oreburgh_Centre_Right", xPercent: 0.45, yPercent: 0.66),
    ],
    "Floaroma": [
        WarpPoint(warpID: "Floaroma_Centre_Entrance", xPercent: 0.59, yPercent: 0.84),
        WarpPoint(warpID: "Floaroma_Mart_Entrance", xPercent: 0.80, yPercent: 0.60),
        WarpPoint(warpID: "Floaroma_Meadow_Entrance", xPercent: 0.24, yPercent: 0.18),
        WarpPoint(warpID: "Floaroma_Flower_Shop", xPercent: 0.69, yPercent: 0.44),
        WarpPoint(warpID: "Floaroma_House_North", xPercent: 0.46, yPercent: 0.53),
        WarpPoint(warpID: "Floaroma_House_South", xPercent: 0.80, yPercent: 0.85),
        WarpPoint(warpID: "Floaroma_Centre_Exit", xPercent: 0.18, yPercent: 0.80),
        WarpPoint(warpID: "Floaroma_Centre_Left", xPercent: 0.07, yPercent: 0.77),
        WarpPoint(warpID: "Floaroma_Centre_Right", xPercent: 0.30, yPercent: 0.77),
    ],
    "Valley Windworks": [
        WarpPoint(warpID: "Valley_Windworks_Entrance", xPercent: 0.55, yPercent: 0.48),
    ],
    "Route 204": [
        WarpPoint(warpID: "Route_204_Cave_South", xPercent: 0.20, yPercent: 0.82),
        WarpPoint(warpID: "Route_204_Cave_North", xPercent: 0.69, yPercent: 0.30),
    ],
    "Route 203": [
        WarpPoint(warpID: "Route_203_Cave", xPercent: 0.56, yPercent: 0.49),
    ],
    "Eterna": [
        WarpPoint(warpID: "Eterna_Centre_Entrance", xPercent: 0.24, yPercent: 0.32),
        WarpPoint(warpID: "Eterna_Dig_House", xPercent: 0.36, yPercent: 0.32),
        WarpPoint(warpID: "Eterna_Mart_Entrance", xPercent: 0.35, yPercent: 0.64),
        WarpPoint(warpID: "Eterna_Gym_Entrance", xPercent: 0.42, yPercent: 0.87),
        WarpPoint(warpID: "Eterna_Gate_South", xPercent: 0.23, yPercent: 0.94),
        WarpPoint(warpID: "Eterna_TG_Building", xPercent: 0.24, yPercent: 0.12),
        WarpPoint(warpID: "Eterna_Condo_Entrance", xPercent: 0.50, yPercent: 0.64),
        WarpPoint(warpID: "Eterna_Bike_Shop", xPercent: 0.37, yPercent: 0.49),
        WarpPoint(warpID: "Eterna_House_North", xPercent: 0.52, yPercent: 0.15),
        WarpPoint(warpID: "Eterna_House_South", xPercent: 0.07, yPercent: 0.88),
        WarpPoint(warpID: "Eterna_House_East", xPercent: 0.80, yPercent: 0.44),
        WarpPoint(warpID: "Eterna_Centre_Exit", xPercent: 0.82, yPercent: 0.77),
        WarpPoint(warpID: "Eterna_Centre_Left", xPercent: 0.70, yPercent: 0.75),
        WarpPoint(warpID: "Eterna_Centre_Right", xPercent: 0.92, yPercent: 0.75),
    ],
    "Eterna Forest": [
        WarpPoint(warpID: "Eterna_Forest_Exit_South", xPercent: 0.32, yPercent: 0.85),
        WarpPoint(warpID: "Eterna_Forest_Exit_North", xPercent: 0.75, yPercent: 0.71),
        WarpPoint(warpID: "Eterna_Forest_Mansion", xPercent: 0.29, yPercent: 0.40),
    ],
    "Hearthome": [
        WarpPoint(warpID: "Hearthome_Centre_Entrance", xPercent: 0.28, yPercent: 0.41),
        WarpPoint(warpID: "Hearthome_Mart_Entrance", xPercent: 0.47, yPercent: 0.63),
        WarpPoint(warpID: "Hearthome_Gate_West", xPercent: 0.13, yPercent: 0.86),
        WarpPoint(warpID: "Hearthome_Gate_South", xPercent: 0.17, yPercent: 0.94),
        WarpPoint(warpID: "Hearthome_Gate_East", xPercent: 0.89, yPercent: 0.85),
        WarpPoint(warpID: "Hearthome_Temple_Entrance", xPercent: 0.20, yPercent: 0.60),
        WarpPoint(warpID: "Hearthome_Gym_Entrance", xPercent: 0.83, yPercent: 0.42),
        WarpPoint(warpID: "Hearthome_Amity_Left", xPercent: 0.18, yPercent: 0.19),
        WarpPoint(warpID: "Hearthome_Amity_Right", xPercent: 0.85, yPercent: 0.19),
        WarpPoint(warpID: "Hearthome_Contest_Entrance", xPercent: 0.505, yPercent: 0.32),
        WarpPoint(warpID: "Hearthome_Condo_North", xPercent: 0.62, yPercent: 0.42),
        WarpPoint(warpID: "Hearthome_Condo_South", xPercent: 0.74, yPercent: 0.63),
        WarpPoint(warpID: "Hearthome_House_Bebe", xPercent: 0.36, yPercent: 0.41),
        WarpPoint(warpID: "Hearthome_Poffin_House", xPercent: 0.65, yPercent: 0.63),
        WarpPoint(warpID: "Hearthome_Fan_Club", xPercent: 0.39, yPercent: 0.63),
        WarpPoint(warpID: "Hearthome_Centre_Exit", xPercent: 0.50, yPercent: 0.17),
        WarpPoint(warpID: "Hearthome_Centre_Left", xPercent: 0.43, yPercent: 0.16),
        WarpPoint(warpID: "Hearthome_Centre_Right", xPercent: 0.56, yPercent: 0.16),
    ],
    "Solaceon": [
        WarpPoint(warpID: "Solaceon_Centre_Entrance", xPercent: 0.38, yPercent: 0.54),
        WarpPoint(warpID: "Solaceon_Mart_Entrance", xPercent: 0.46, yPercent: 0.82),
        WarpPoint(warpID: "Solaceon_Daycare_Entrance", xPercent: 0.18, yPercent: 0.28),
        WarpPoint(warpID: "Solaceon_Ruins_Entrance", xPercent: 0.86, yPercent: 0.52),
        WarpPoint(warpID: "Solaceon_Tree_House_1", xPercent: 0.59, yPercent: 0.32),
        WarpPoint(warpID: "Solaceon_Tree_House_2", xPercent: 0.64, yPercent: 0.54),
        WarpPoint(warpID: "Solaceon_News_House", xPercent: 0.46, yPercent: 0.54),
        WarpPoint(warpID: "Solaceon_House_North", xPercent: 0.37, yPercent: 0.30),
        WarpPoint(warpID: "Solaceon_Centre_Exit", xPercent: 0.11, yPercent: 0.94),
        WarpPoint(warpID: "Solaceon_Centre_Left", xPercent: 0.05, yPercent: 0.90),
        WarpPoint(warpID: "Solaceon_Centre_Right", xPercent: 0.18, yPercent: 0.90),
    ],
    "Solaceon Ruins": [
        WarpPoint(warpID: "Solaceon_Ruins_1F_Exit", xPercent: 0.16, yPercent: 0.43),
        WarpPoint(warpID: "Solaceon_Ruins_1F_Bottom_Right", xPercent: 0.23, yPercent: 0.43),
        WarpPoint(warpID: "Solaceon_Ruins_1F_Top_Left", xPercent: 0.13, yPercent: 0.18),
        WarpPoint(warpID: "Solaceon_Ruins_1F_Top_Right", xPercent: 0.19, yPercent: 0.18),
        WarpPoint(warpID: "Solaceon_Ruins_B1F_Bottom_Left", xPercent: 0.47, yPercent: 0.42),
        WarpPoint(warpID: "Solaceon_Ruins_B1F_Bottom_Right", xPercent: 0.53, yPercent: 0.42),
        WarpPoint(warpID: "Solaceon_Ruins_B1F_Top_Left", xPercent: 0.47, yPercent: 0.18),
        WarpPoint(warpID: "Solaceon_Ruins_B1F_Top_Right", xPercent: 0.53, yPercent: 0.18),
        WarpPoint(warpID: "Solaceon_Ruins_B2F_Bottom_Left", xPercent: 0.82, yPercent: 0.43),
        WarpPoint(warpID: "Solaceon_Ruins_B2F_Bottom_Right", xPercent: 0.88, yPercent: 0.43),
        WarpPoint(warpID: "Solaceon_Ruins_B2F_Top_Left", xPercent: 0.82, yPercent: 0.18),
        WarpPoint(warpID: "Solaceon_Ruins_B2F_Top_Right", xPercent: 0.88, yPercent: 0.18),
        WarpPoint(warpID: "Solaceon_Ruins_B3F_1_Bottom_Left", xPercent: 0.12, yPercent: 0.88),
        WarpPoint(warpID: "Solaceon_Ruins_B3F_1_Bottom_Right", xPercent: 0.19, yPercent: 0.88),
        WarpPoint(warpID: "Solaceon_Ruins_B3F_1_Top_Left", xPercent: 0.12, yPercent: 0.68),
        WarpPoint(warpID: "Solaceon_Ruins_B3F_1_Top_Right", xPercent: 0.19, yPercent: 0.68),
        WarpPoint(warpID: "Solaceon_Ruins_B3F_2_Bottom_Left", xPercent: 0.48, yPercent: 0.93),
        WarpPoint(warpID: "Solaceon_Ruins_B3F_2_Bottom_Right", xPercent: 0.54, yPercent: 0.93),
        WarpPoint(warpID: "Solaceon_Ruins_B3F_2_Top_Left", xPercent: 0.48, yPercent: 0.68),
        WarpPoint(warpID: "Solaceon_Ruins_B4F_Bottom_Left", xPercent: 0.77, yPercent: 0.93),
        WarpPoint(warpID: "Solaceon_Ruins_B4F_Bottom_Right", xPercent: 0.86, yPercent: 0.93),
        WarpPoint(warpID: "Solaceon_Ruins_B4F_Top_Left", xPercent: 0.77, yPercent: 0.67),
        WarpPoint(warpID: "Solaceon_Ruins_B4F_Top_Right", xPercent: 0.86, yPercent: 0.67),
    ],
    "Veilstone": [
        WarpPoint(warpID: "Veilstone_Centre_Entrance", xPercent: 0.73, yPercent: 0.57),
        WarpPoint(warpID: "Veilstone_Dept_Store", xPercent: 0.47, yPercent: 0.46),
        WarpPoint(warpID: "Veilstone_Warehouse_Entrance", xPercent: 0.46, yPercent: 0.24),
        WarpPoint(warpID: "Veilstone_GHQ_Door_1", xPercent: 0.68, yPercent: 0.18),
        WarpPoint(warpID: "Veilstone_GHQ_Door_2", xPercent: 0.73, yPercent: 0.18),
        WarpPoint(warpID: "Veilstone_GHQ_Door_3", xPercent: 0.78, yPercent: 0.18),
        WarpPoint(warpID: "Veilstone_Gate_West", xPercent: 0.13, yPercent: 0.37),
        WarpPoint(warpID: "Veilstone_Gate_South", xPercent: 0.75, yPercent: 0.98),
        WarpPoint(warpID: "Veilstone_Game_Corner", xPercent: 0.55, yPercent: 0.78),
        WarpPoint(warpID: "Veilstone_Corner_Redeem", xPercent: 0.72, yPercent: 0.78),
        WarpPoint(warpID: "Veilstone_PC_House_1", xPercent: 0.63, yPercent: 0.43),
        WarpPoint(warpID: "Veilstone_PC_House_2", xPercent: 0.73, yPercent: 0.43),
        WarpPoint(warpID: "Veilstone_Gym_Entrance", xPercent: 0.20, yPercent: 0.59),
        WarpPoint(warpID: "Veilstone_Gym_House_1", xPercent: 0.30, yPercent: 0.79),
        WarpPoint(warpID: "Veilstone_Gym_House_2", xPercent: 0.39, yPercent: 0.79),
        WarpPoint(warpID: "Veilstone_Centre_Exit", xPercent: 0.16, yPercent: 0.18),
        WarpPoint(warpID: "Veilstone_Centre_Left", xPercent: 0.11, yPercent: 0.15),
        WarpPoint(warpID: "Veilstone_Centre_Right", xPercent: 0.22, yPercent: 0.15),
    ],
    "Dept Store": [
        WarpPoint(warpID: "Dept_Store_B1F", xPercent: 0.28, yPercent: 0.83),
        WarpPoint(warpID: "Dept_Store_1F_Exit", xPercent: 0.28, yPercent: 0.60),
        WarpPoint(warpID: "Dept_Store_1F_Down", xPercent: 0.19, yPercent: 0.52),
        WarpPoint(warpID: "Dept_Store_1F_Up", xPercent: 0.36, yPercent: 0.52),
        WarpPoint(warpID: "Dept_Store_2F_Down", xPercent: 0.18, yPercent: 0.18),
        WarpPoint(warpID: "Dept_Store_2F_Up", xPercent: 0.36, yPercent: 0.18),
        WarpPoint(warpID: "Dept_Store_3F_Down", xPercent: 0.66, yPercent: 0.86),
        WarpPoint(warpID: "Dept_Store_3F_Up", xPercent: 0.84, yPercent: 0.86),
        WarpPoint(warpID: "Dept_Store_4F_Down", xPercent: 0.67, yPercent: 0.52),
        WarpPoint(warpID: "Dept_Store_4F_Up", xPercent: 0.84, yPercent: 0.52),
        WarpPoint(warpID: "Dept_Store_5F_Down", xPercent: 0.66, yPercent: 0.18),
    ],
    "Pastoria": [
        WarpPoint(warpID: "Pastoria_Centre_Entrance", xPercent: 0.37, yPercent: 0.38),
        WarpPoint(warpID: "Pastoria_Mart_Entrance", xPercent: 0.38, yPercent: 0.86),
        WarpPoint(warpID: "Pastoria_Gym_Entrance", xPercent: 0.19, yPercent: 0.57),
        WarpPoint(warpID: "Pastoria_Gate_East", xPercent: 0.96, yPercent: 0.29),
        WarpPoint(warpID: "Pastoria_Gate_House", xPercent: 0.75, yPercent: 0.44),
        WarpPoint(warpID: "Pastoria_Gym_House", xPercent: 0.37, yPercent: 0.53),
        WarpPoint(warpID: "Pastoria_House_Left", xPercent: 0.38, yPercent: 0.71),
        WarpPoint(warpID: "Pastoria_House_Right", xPercent: 0.55, yPercent: 0.71),
        WarpPoint(warpID: "Pastoria_House_South", xPercent: 0.19, yPercent: 0.86),
        WarpPoint(warpID: "Pastoria_Centre_Exit", xPercent: 0.755, yPercent: 0.97),
        WarpPoint(warpID: "Pastoria_Centre_Left", xPercent: 0.68, yPercent: 0.94),
        WarpPoint(warpID: "Pastoria_Centre_Right", xPercent: 0.82, yPercent: 0.94),
    ],
    "Route 212": [
        WarpPoint(warpID: "Route_212_House", xPercent: 0.70, yPercent: 0.88),
        WarpPoint(warpID: "Backlot_Mansion_Entrance", xPercent: 0.74, yPercent: 0.43),
        WarpPoint(warpID: "Route_212_Gate", xPercent: 0.21, yPercent: 0.27),
    ],
    "Backlot Mansion": [
        WarpPoint(warpID: "Backlot_Mansion_Left_1", xPercent: 0.37, yPercent: 0.40),
        WarpPoint(warpID: "Backlot_Mansion_Left_2", xPercent: 0.23, yPercent: 0.40),
        WarpPoint(warpID: "Backlot_Mansion_Left_3", xPercent: 0.10, yPercent: 0.40),
        WarpPoint(warpID: "Backlot_Mansion_Right", xPercent: 0.84, yPercent: 0.40),
        WarpPoint(warpID: "Backlot_Mansion_Top", xPercent: 0.58, yPercent: 0.25),
        WarpPoint(warpID: "Backlot_Mansion_Bottom", xPercent: 0.58, yPercent: 0.80),
    ],
    "Celestic": [
        WarpPoint(warpID: "Celestic_Centre_Entrance", xPercent: 0.52, yPercent: 0.85),
        WarpPoint(warpID: "Celestic_House_Left", xPercent: 0.05, yPercent: 0.30),
        WarpPoint(warpID: "Celestic_House_Right", xPercent: 0.54, yPercent: 0.30),
        WarpPoint(warpID: "Celestic_House_South", xPercent: 0.14, yPercent: 0.85),
        WarpPoint(warpID: "Celestic_Hall_North", xPercent: 0.33, yPercent: 0.29),
        WarpPoint(warpID: "Celestic_Ruins_Entrance", xPercent: 0.33, yPercent: 0.48),
        WarpPoint(warpID: "Celestic_Centre_Exit", xPercent: 0.85, yPercent: 0.31),
        WarpPoint(warpID: "Celestic_Centre_Left", xPercent: 0.77, yPercent: 0.27),
        WarpPoint(warpID: "Celestic_Centre_Right", xPercent: 0.94, yPercent: 0.27),
    ],
    "Canalave": [
        WarpPoint(warpID: "Canalave_Centre_Entrance", xPercent: 0.54, yPercent: 0.26),
        WarpPoint(warpID: "Canalave_Mart_Entrance", xPercent: 0.43, yPercent: 0.55),
        WarpPoint(warpID: "Canalave_Library_Entrance", xPercent: 0.12, yPercent: 0.21),
        WarpPoint(warpID: "Canalave_Gym_Entrance", xPercent: 0.16, yPercent: 0.40),
        WarpPoint(warpID: "Canalave_Gate_East", xPercent: 0.74, yPercent: 0.88),
        WarpPoint(warpID: "Canalave_Locked_House", xPercent: 0.54, yPercent: 0.11),
        WarpPoint(warpID: "Canalave_House_Top_Left", xPercent: 0.14, yPercent: 0.56),
        WarpPoint(warpID: "Canalave_House_Bottom_Left", xPercent: 0.16, yPercent: 0.70),
        WarpPoint(warpID: "Canalave_House_Top_Right", xPercent: 0.44, yPercent: 0.44),
        WarpPoint(warpID: "Canalave_House_Bottom_Right", xPercent: 0.46, yPercent: 0.70),
        WarpPoint(warpID: "Canalave_Centre_Exit", xPercent: 0.82, yPercent: 0.65),
        WarpPoint(warpID: "Canalave_Centre_Left", xPercent: 0.71, yPercent: 0.61),
        WarpPoint(warpID: "Canalave_Centre_Right", xPercent: 0.92, yPercent: 0.61),
    ],
    "Iron Island": [
        WarpPoint(warpID: "Iron_Island_House", xPercent: 0.15, yPercent: 0.49),
        WarpPoint(warpID: "Iron_Island_Entrance", xPercent: 0.23, yPercent: 0.18),
        WarpPoint(warpID: "Iron_Island_Gated_Exit", xPercent: 0.05, yPercent: 0.36),
        WarpPoint(warpID: "Iron_Island_Room_1_Exit", xPercent: 0.42, yPercent: 0.27),
        WarpPoint(warpID: "Iron_Island_Room_1_Left", xPercent: 0.39, yPercent: 0.15),
        WarpPoint(warpID: "Iron_Island_Room_1_Right", xPercent: 0.45, yPercent: 0.15),
        WarpPoint(warpID: "Iron_Island_Room_2_Up", xPercent: 0.69, yPercent: 0.18),
        WarpPoint(warpID: "Iron_Island_Room_2_Left", xPercent: 0.75, yPercent: 0.89),
        WarpPoint(warpID: "Iron_Island_Room_2_Right", xPercent: 0.89, yPercent: 0.89),
        WarpPoint(warpID: "Iron_Island_Room_3_Cave", xPercent: 0.55, yPercent: 0.47),
        WarpPoint(warpID: "Iron_Island_Room_2_Exit_Left", xPercent: 0.37, yPercent: 0.50),
        WarpPoint(warpID: "Iron_Island_Room_2_Exit_Right", xPercent: 0.53, yPercent: 0.92),
    ],
    "Snowpoint": [
        WarpPoint(warpID: "Snowpoint_Centre_Entrance", xPercent: 0.73, yPercent: 0.91),
        WarpPoint(warpID: "Snowpoint_Mart_Entrance", xPercent: 0.04, yPercent: 0.89),
        WarpPoint(warpID: "Snowpoint_Gym_Entrance", xPercent: 0.41, yPercent: 0.72),
        WarpPoint(warpID: "Snowpoint_House_Left", xPercent: 0.04, yPercent: 0.44),
        WarpPoint(warpID: "Snowpoint_House_Right", xPercent: 0.73, yPercent: 0.44),
        WarpPoint(warpID: "Snowpoint_Temple_Entrance", xPercent: 0.39, yPercent: 0.24),
        WarpPoint(warpID: "Snowpoint_Centre_Exit", xPercent: 0.81, yPercent: 0.73),
        WarpPoint(warpID: "Snowpoint_Centre_Left", xPercent: 0.69, yPercent: 0.71),
        WarpPoint(warpID: "Snowpoint_Centre_Right", xPercent: 0.93, yPercent: 0.71),
    ],
    "Route 217": [
        WarpPoint(warpID: "Route_217_House_Top", xPercent: 0.80, yPercent: 0.70),
        WarpPoint(warpID: "Route_217_House_Bottom", xPercent: 0.22, yPercent: 0.78),
    ],
    "Route 216": [
        WarpPoint(warpID: "Route_216_House", xPercent: 0.20, yPercent: 0.54),
        WarpPoint(warpID: "Route_216_Cave_Exit", xPercent: 0.75, yPercent: 0.56),
    ],
    "Sunyshore": [
        WarpPoint(warpID: "Sunyshore_Centre_Entrance", xPercent: 0.46, yPercent: 0.84),
        WarpPoint(warpID: "Sunyshore_Mart_Entrance", xPercent: 0.35, yPercent: 0.58),
        WarpPoint(warpID: "Sunyshore_Gym_Entrance", xPercent: 0.21, yPercent: 0.17),
        WarpPoint(warpID: "Sunyshore_Seal_Shop", xPercent: 0.29, yPercent: 0.48),
        WarpPoint(warpID: "Sunyshore_Lighthouse_Entrance", xPercent: 0.87, yPercent: 0.89),
        WarpPoint(warpID: "Sunyshore_Gate_South", xPercent: 0.04, yPercent: 0.92),
        WarpPoint(warpID: "Sunyshore_Mart_House", xPercent: 0.21, yPercent: 0.57),
        WarpPoint(warpID: "Sunyshore_House_Left", xPercent: 0.70, yPercent: 0.10),
        WarpPoint(warpID: "Sunyshore_House_Right", xPercent: 0.83, yPercent: 0.10),
        WarpPoint(warpID: "Sunyshore_Rock_House", xPercent: 0.91, yPercent: 0.55),
        WarpPoint(warpID: "Sunyshore_Centre_Exit", xPercent: 0.88, yPercent: 0.38),
        WarpPoint(warpID: "Sunyshore_Centre_Left", xPercent: 0.82, yPercent: 0.36),
        WarpPoint(warpID: "Sunyshore_Centre_Right", xPercent: 0.94, yPercent: 0.36),
    ],
    "Valor Lakefront": [
        WarpPoint(warpID: "Valor_House_Bottom", xPercent: 0.49, yPercent: 0.94),
        WarpPoint(warpID: "Valor_House_Rock_Climb", xPercent: 0.70, yPercent: 0.81),
        WarpPoint(warpID: "Valor_House_Bottom_Left", xPercent: 0.37, yPercent: 0.81),
        WarpPoint(warpID: "Valor_House_Bottom_Right", xPercent: 0.59, yPercent: 0.92),
        WarpPoint(warpID: "Valor_Cafe_Entrance", xPercent: 0.49, yPercent: 0.56),
        WarpPoint(warpID: "Valor_House_West", xPercent: 0.11, yPercent: 0.55),
        WarpPoint(warpID: "Valor_House_North", xPercent: 0.70, yPercent: 0.39),
        WarpPoint(warpID: "Valor_Lake_Entrance", xPercent: 0.74, yPercent: 0.08),
    ],
    "Lake Valor": [
        WarpPoint(warpID: "Valor_Lake_Exit", xPercent: 0.83, yPercent: 0.13),
        WarpPoint(warpID: "Valor_Lake_Cave", xPercent: 0.50, yPercent: 0.56),
    ],
    "Route 222": [
        WarpPoint(warpID: "Route_222_House_Left", xPercent: 0.17, yPercent: 0.56),
        WarpPoint(warpID: "Route_222_House_Right", xPercent: 0.41, yPercent: 0.56),
        WarpPoint(warpID: "Route_222_Gate", xPercent: 0.81, yPercent: 0.65),
    ],
    "Route 214": [
        WarpPoint(warpID: "Route_214_Cave_Entrance", xPercent: 0.35, yPercent: 0.74),
        WarpPoint(warpID: "Route_214_Gate_North", xPercent: 0.50, yPercent: 0.30),
    ],
    "Fight Area": [
        WarpPoint(warpID: "Fight_Area_Centre_Entrance", xPercent: 0.52, yPercent: 0.42),
        WarpPoint(warpID: "Fight_Area_Mart_Entrance", xPercent: 0.85, yPercent: 0.43),
        WarpPoint(warpID: "Fight_Area_House_Top", xPercent: 0.70, yPercent: 0.66),
        WarpPoint(warpID: "Fight_Area_House_Bottom", xPercent: 0.70, yPercent: 0.82),
        WarpPoint(warpID: "Fight_Area_Frontier_Entrance", xPercent: 0.71, yPercent: 0.27),
        WarpPoint(warpID: "Fight_Area_Gate_North", xPercent: 0.08, yPercent: 0.21),
        WarpPoint(warpID: "Fight_Area_Centre_Exit", xPercent: 0.24, yPercent: 0.96),
        WarpPoint(warpID: "Fight_Area_Centre_Left", xPercent: 0.14, yPercent: 0.91),
        WarpPoint(warpID: "Fight_Area_Centre_Right", xPercent: 0.35, yPercent: 0.91),
    ],
    "Resort Area": [
        WarpPoint(warpID: "Resort_Area_Centre_Entrance", xPercent: 0.05, yPercent: 0.80),
        WarpPoint(warpID: "Resort_Area_House", xPercent: 0.22, yPercent: 0.39),
        WarpPoint(warpID: "Resort_Area_Ribbons", xPercent: 0.52, yPercent: 0.35),
        WarpPoint(warpID: "Resort_Area_Villa", xPercent: 0.48, yPercent: 0.70),
        WarpPoint(warpID: "Resort_Area_Centre_Exit", xPercent: 0.85, yPercent: 0.32),
        WarpPoint(warpID: "Resort_Area_Centre_Left", xPercent: 0.76, yPercent: 0.28),
        WarpPoint(warpID: "Resort_Area_Centre_Right", xPercent: 0.93, yPercent: 0.28),
    ],
    "Route 228": [
        WarpPoint(warpID: "Route_228_House_Top", xPercent: 0.77, yPercent: 0.87),
        WarpPoint(warpID: "Route_228_Gate_North", xPercent: 0.34, yPercent: 0.36),
        WarpPoint(warpID: "Route_228_House_Bottom", xPercent: 0.19, yPercent: 0.87),
        WarpPoint(warpID: "Route_228_Cave", xPercent: 0.81, yPercent: 0.30),
    ],
    "Jubilife TV": [
        WarpPoint(warpID: "Jubilife_TV_1F_Exit", xPercent: 0.21, yPercent: 0.91),
        WarpPoint(warpID: "Jubilife_TV_1F_Up", xPercent: 0.34, yPercent: 0.59),
        WarpPoint(warpID: "Jubilife_TV_2F_Down", xPercent: 0.16, yPercent: 0.12),
        WarpPoint(warpID: "Jubilife_TV_2F_Up", xPercent: 0.34, yPercent: 0.13),
        WarpPoint(warpID: "Jubilife_TV_2F_Door", xPercent: 0.07, yPercent: 0.13),
        WarpPoint(warpID: "Jubilife_TV_3F_Down", xPercent: 0.71, yPercent: 0.67),
        WarpPoint(warpID: "Jubilife_TV_3F_Up", xPercent: 0.85, yPercent: 0.63),
        WarpPoint(warpID: "Jubilife_TV_3F_Door_Left", xPercent: 0.55, yPercent: 0.63),
        WarpPoint(warpID: "Jubilife_TV_3F_Door_Right", xPercent: 0.63, yPercent: 0.63),
        WarpPoint(warpID: "Jubilife_TV_4F_Down", xPercent: 0.66, yPercent: 0.18),
    ],
    "Old Chateau": [
        WarpPoint(warpID: "Old_Chateau_Room_Top", xPercent: 0.50, yPercent: 0.42),
        WarpPoint(warpID: "Old_Chateau_Room_Left", xPercent: 0.32, yPercent: 0.54),
        WarpPoint(warpID: "Old_Chateau_Room_Right", xPercent: 0.68, yPercent: 0.54),
        WarpPoint(warpID: "Old_Chateau_Room_Bottom", xPercent: 0.50, yPercent: 0.62),
        WarpPoint(warpID: "Old_Chateau_Room_Exit", xPercent: 0.50, yPercent: 0.90),
        WarpPoint(warpID: "Old_Chateau_Corridor_Exit", xPercent: 0.50, yPercent: 0.22),
        WarpPoint(warpID: "Old_Chateau_Corridor_Middle", xPercent: 0.50, yPercent: 0.10),
        WarpPoint(warpID: "Old_Chateau_Corridor_Left_1", xPercent: 0.29, yPercent: 0.10),
        WarpPoint(warpID: "Old_Chateau_Corridor_Left_2", xPercent: 0.11, yPercent: 0.10),
        WarpPoint(warpID: "Old_Chateau_Corridor_Right_1", xPercent: 0.71, yPercent: 0.10),
        WarpPoint(warpID: "Old_Chateau_Corridor_Right_2", xPercent: 0.89, yPercent: 0.10),
    ],
    "Floaroma Meadow": [
        WarpPoint(warpID: "Floaroma_Meadow_Exit_North", xPercent: 0.72, yPercent: 0.33),
        WarpPoint(warpID: "Floaroma_Meadow_Exit_South", xPercent: 0.20, yPercent: 0.84),
        WarpPoint(warpID: "Floaroma_Meadow_House", xPercent: 0.70, yPercent: 0.90),
    ],
    "Poketch": [
        WarpPoint(warpID: "Poketch_Company_Exit_Left", xPercent: 0.23, yPercent: 0.80),
        WarpPoint(warpID: "Poketch_Company_Exit_Right", xPercent: 0.79, yPercent: 0.80),
        WarpPoint(warpID: "Poketch_Company_Stairs", xPercent: 0.32, yPercent: 0.34),
    ],
    "TG Eterna": [
        WarpPoint(warpID: "TG_Eterna_1F_Exit", xPercent: 0.23, yPercent: 0.82),
        WarpPoint(warpID: "TG_Eterna_1F_Rotom_Room", xPercent: 0.04, yPercent: 0.59),
        WarpPoint(warpID: "TG_Eterna_1F_Stairs_Left", xPercent: 0.30, yPercent: 0.65),
        WarpPoint(warpID: "TG_Eterna_1F_Stairs_Right", xPercent: 0.44, yPercent: 0.65),
        WarpPoint(warpID: "TG_Eterna_2F_Down", xPercent: 0.18, yPercent: 0.11),
        WarpPoint(warpID: "TG_Eterna_2F_Up_Left", xPercent: 0.30, yPercent: 0.11),
        WarpPoint(warpID: "TG_Eterna_2F_Up_Right", xPercent: 0.44, yPercent: 0.11),
        WarpPoint(warpID: "TG_Eterna_3F_Down", xPercent: 0.54, yPercent: 0.68),
        WarpPoint(warpID: "TG_Eterna_3F_Up_Left", xPercent: 0.82, yPercent: 0.68),
        WarpPoint(warpID: "TG_Eterna_3F_Up_Right", xPercent: 0.94, yPercent: 0.68),
    ],
    "Oreburgh Gate": [
        WarpPoint(warpID: "Oreburgh_Gate_Exit_Left", xPercent: 0.13, yPercent: 0.80),
        WarpPoint(warpID: "Oreburgh_Gate_Exit_Right", xPercent: 0.88, yPercent: 0.81),
        WarpPoint(warpID: "Oreburgh_Gate_Stairs", xPercent: 0.64, yPercent: 0.19),
    ],
    "Galactic HQ": [
        WarpPoint(warpID: "GHQ_Lobby_Exit_Left", xPercent: 0.42, yPercent: 0.35),
        WarpPoint(warpID: "GHQ_Lobby_Exit_Right", xPercent: 0.75, yPercent: 0.35),
        WarpPoint(warpID: "GHQ_Lobby_Stairs", xPercent: 0.61, yPercent: 0.24),
        WarpPoint(warpID: "GHQ_Big_Floor_Stairs", xPercent: 0.04, yPercent: 0.64),
        WarpPoint(warpID: "GHQ_Big_Floor_Warp_TV", xPercent: 0.39, yPercent: 0.61),
        WarpPoint(warpID: "GHQ_Big_Floor_Warp_Top", xPercent: 0.62, yPercent: 0.62),
        WarpPoint(warpID: "GHQ_Big_Floor_Warp_Bottom", xPercent: 0.62, yPercent: 0.79),
        WarpPoint(warpID: "GHQ_Basement_Stairs_Left", xPercent: 0.05, yPercent: 0.21),
        WarpPoint(warpID: "GHQ_Basement_Stairs_Right", xPercent: 0.20, yPercent: 0.22),
        WarpPoint(warpID: "GHQ_Basement_Stairs_Top", xPercent: 0.16, yPercent: 0.06),
        WarpPoint(warpID: "GHQ_Warp_Room_Stairs", xPercent: 0.88, yPercent: 0.80),
        WarpPoint(warpID: "GHQ_Warp_Room_Warp_Right", xPercent: 0.70, yPercent: 0.93),
        WarpPoint(warpID: "GHQ_Warp_Room_Warp_Middle", xPercent: 0.66, yPercent: 0.93),
        WarpPoint(warpID: "GHQ_Warp_Room_Warp_Left", xPercent: 0.63, yPercent: 0.98),
        WarpPoint(warpID: "GHQ_Stairs_Room_Stairs_Up", xPercent: 0.30, yPercent: 0.48),
        WarpPoint(warpID: "GHQ_Stairs_Room_Stairs_Down", xPercent: 0.23, yPercent: 0.48),
        WarpPoint(warpID: "GHQ_Stairs_Room_Warp", xPercent: 0.13, yPercent: 0.48),
        WarpPoint(warpID: "GHQ_Two_Warp_Left", xPercent: 0.30, yPercent: 0.05),
        WarpPoint(warpID: "GHQ_Two_Warp_Right", xPercent: 0.34, yPercent: 0.05),
        WarpPoint(warpID: "GHQ_Two_Warp_Stairs", xPercent: 0.44, yPercent: 0.06),
        WarpPoint(warpID: "GHQ_Cyrus_Warp_Green", xPercent: 0.94, yPercent: 0.68),
        WarpPoint(warpID: "GHQ_Cyrus_Warp_Top_Right", xPercent: 0.96, yPercent: 0.49),
        WarpPoint(warpID: "GHQ_Cyrus_Warp_Room", xPercent: 0.78, yPercent: 0.48),
        WarpPoint(warpID: "GHQ_Cyrus_Stairs", xPercent: 0.71, yPercent: 0.67),
    ],
    "Acuity Lakefront": [
        WarpPoint(warpID: "Acuity_Lake_Entrance", xPercent: 0.34, yPercent: 0.61),
    ],
    "Lake Acuity": [
        WarpPoint(warpID: "Aquity_Lake_Exit", xPercent: 0.10, yPercent: 0.97),
        WarpPoint(warpID: "Aquity_Lake_Cave", xPercent: 0.47, yPercent: 0.64),
    ],
    "Verity Lakefront": [
        WarpPoint(warpID: "Verity_Lake_Entrance", xPercent: 0.46, yPercent: 0.45),
    ],
    "Lake Verity": [
        WarpPoint(warpID: "Verity_Lake_Exit", xPercent: 0.76, yPercent: 0.80),
        WarpPoint(warpID: "Verity_Lake_Cave", xPercent: 0.50, yPercent: 0.47),
    ],
    "Mt Coronet": [
        WarpPoint(warpID: "Coronet_Cyrus_Exit_Left", xPercent: 0.06, yPercent: 0.47),
        WarpPoint(warpID: "Coronet_Cyrus_Exit_Right", xPercent: 0.31, yPercent: 0.62),
        WarpPoint(warpID: "Coronet_Cyrus_Exit_North", xPercent: 0.30, yPercent: 0.40),
        WarpPoint(warpID: "Coronet_Big_Room_West", xPercent: 0.49, yPercent: 0.56),
        WarpPoint(warpID: "Coronet_Big_Room_East", xPercent: 0.93, yPercent: 0.47),
        WarpPoint(warpID: "Coronet_Big_Room_North", xPercent: 0.65, yPercent: 0.11),
        WarpPoint(warpID: "Coronet_Big_Room_South", xPercent: 0.81, yPercent: 0.88),
        WarpPoint(warpID: "Coronet_Waterfall_Room_Entrance_Left", xPercent: 0.08, yPercent: 0.99),
        WarpPoint(warpID: "Coronet_Waterall_Room_Entrance_Bottom", xPercent: 0.39, yPercent: 0.99),
        WarpPoint(warpID: "Coronet_Waterfall_Room_Exit", xPercent: 0.42, yPercent: 0.82),
        WarpPoint(warpID: "Coronet_Waterfall_Room_Waterfall", xPercent: 0.19, yPercent: 0.81),
        WarpPoint(warpID: "Coronet_Looker_Room_Exit_North", xPercent: 0.07, yPercent: 0.03),
        WarpPoint(warpID: "Coronet_Looker_Room_Exit_East", xPercent: 0.25, yPercent: 0.19),
        WarpPoint(warpID: "Coronet_Looker_Room_Exit_South", xPercent: 0.04, yPercent: 0.27),
        WarpPoint(warpID: "Coronet_Stairs_Left", xPercent: 0.53, yPercent: 0.32),
        WarpPoint(warpID: "Coronet_Stairs_Right", xPercent: 0.59, yPercent: 0.32),
        WarpPoint(warpID: "Coronet_Stairs_Cave_Exit", xPercent: 0.43, yPercent: 0.32),
        WarpPoint(warpID: "Coronet_Two_Caves_Exit", xPercent: 0.35, yPercent: 0.03),
        WarpPoint(warpID: "Coronet_Two_Caves_Middle", xPercent: 0.49, yPercent: 0.03),
        WarpPoint(warpID: "Coronet_Two_Caves_Stairs", xPercent: 0.43, yPercent: 0.14),
    ],
    "Mt Coronet Peak": [
        WarpPoint(warpID: "Coronet_Peak_Top_Bottom_Cave", xPercent: 0.81, yPercent: 0.40),
        WarpPoint(warpID: "Coronet_Peak_Top_Middle_Cave", xPercent: 0.86, yPercent: 0.26),
        WarpPoint(warpID: "Coronet_Peak_Top_Upper_Cave", xPercent: 0.15, yPercent: 0.10),
        WarpPoint(warpID: "Coronet_Peak_Bottom_Right_Cave", xPercent: 0.74, yPercent: 0.68),
        WarpPoint(warpID: "Coronet_Peak_Bottom_Left_Cave", xPercent: 0.14, yPercent: 0.66),
        WarpPoint(warpID: "Coronet_Peak_Bottom_Lower_Cave", xPercent: 0.17, yPercent: 0.97),
    ],
    "Pokemon League": [
        WarpPoint(warpID: "League_Centre_Small_Entrance", xPercent: 0.20, yPercent: 0.51),
        WarpPoint(warpID: "League_Centre_Small_Exit", xPercent: 0.13, yPercent: 0.92),
        WarpPoint(warpID: "League_Centre_Small_Left", xPercent: 0.05, yPercent: 0.89),
        WarpPoint(warpID: "League_Centre_Small_Right", xPercent: 0.22, yPercent: 0.89),
        WarpPoint(warpID: "League_Centre_Big_Exit", xPercent: 0.81, yPercent: 0.72),
        WarpPoint(warpID: "League_Centre_Big_E4", xPercent: 0.81, yPercent: 0.42),
        WarpPoint(warpID: "League_Centre_Big_Up", xPercent: 0.67, yPercent: 0.75),
        WarpPoint(warpID: "League_Centre_Big_Down", xPercent: 0.70, yPercent: 0.85),
        WarpPoint(warpID: "Victory_Road_Entrance", xPercent: 0.37, yPercent: 0.49),
    ],
    "Pokemon League Outside": [
        WarpPoint(warpID: "Pokemon_League_Entrance", xPercent: 0.50, yPercent: 0.21),
        WarpPoint(warpID: "Pokemon_League_E4_Exit", xPercent: 0.65, yPercent: 0.63),
    ],
    "Victory Road": [
        WarpPoint(warpID: "Victory_Road_Exit_South", xPercent: 0.27, yPercent: 0.98),
        WarpPoint(warpID: "Victory_Road_Exit_North", xPercent: 0.57, yPercent: 0.10),
        WarpPoint(warpID: "Victory_Road_Main_Stairs_Right_Top", xPercent: 0.64, yPercent: 0.46),
        WarpPoint(warpID: "Victory_Road_Main_Stairs_Right_Middle", xPercent: 0.66, yPercent: 0.75),
        WarpPoint(warpID: "Victory_Road_Main_Stairs_Left_Top", xPercent: 0.07, yPercent: 0.42),
        WarpPoint(warpID: "Victory_Road_Main_Stairs_Left_Middle", xPercent: 0.07, yPercent: 0.63),
        WarpPoint(warpID: "Victory_Road_Main_Stairs_Left_Bottom", xPercent: 0.13, yPercent: 0.81),
        WarpPoint(warpID: "Victory_Road_Main_Cave", xPercent: 0.70, yPercent: 0.59),
        WarpPoint(warpID: "Victory_Road_Water_Stairs_Top", xPercent: 0.89, yPercent: 0.06),
        WarpPoint(warpID: "Victory_Road_Water_Stairs_Middle", xPercent: 0.92, yPercent: 0.35),
        WarpPoint(warpID: "Victory_Road_Water_Stairs_Bottom", xPercent: 0.93, yPercent: 0.45),
    ],
    "Route 227": [
        WarpPoint(warpID: "Route_227_House", xPercent: 0.49, yPercent: 0.65),
    ],
    "Stark Mountain": [
        WarpPoint(warpID: "Stark_Mountain_Entrance", xPercent: 0.45, yPercent: 0.30),
    ],
    "Route 226": [
        WarpPoint(warpID: "Route_226_House", xPercent: 0.26, yPercent: 0.54),
        WarpPoint(warpID: "Route_226_Gate", xPercent: 0.85, yPercent: 0.63),
    ],
    "Route 205": [
        WarpPoint(warpID: "Eterna_Forest_Entrance", xPercent: 0.25, yPercent: 0.34),
        WarpPoint(warpID: "Route_205_House", xPercent: 0.52, yPercent: 0.85),
        WarpPoint(warpID: "Route_205_Forest_Exit", xPercent: 0.85, yPercent: 0.52),
    ],
    "Route 206": [
        WarpPoint(warpID: "Route_206_Cave_Entrance", xPercent: 0.72, yPercent: 0.19),
        WarpPoint(warpID: "Route_206_Hidden_Cave_Entrance", xPercent: 0.37, yPercent: 0.27),
        WarpPoint(warpID: "Bicycle_Road_Entrance", xPercent: 0.45, yPercent: 0.97),
    ],
    "Route 207": [
        WarpPoint(warpID: "Route_207_Cave", xPercent: 0.63, yPercent: 0.59),
    ],
    "Route 208": [
        WarpPoint(warpID: "Route_208_Cave", xPercent: 0.17, yPercent: 0.27),
        WarpPoint(warpID: "Route_208_House", xPercent: 0.75, yPercent: 0.36),
        WarpPoint(warpID: "Route_208_Gate", xPercent: 0.91, yPercent: 0.73),
    ],
    "Route 211": [
        WarpPoint(warpID: "Route_211_Cave_West", xPercent: 0.17, yPercent: 0.54),
        WarpPoint(warpID: "Route_211_Cave_East", xPercent: 0.74, yPercent: 0.52),
    ],
    "Route 213": [
        WarpPoint(warpID: "Route_213_Gate", xPercent: 0.30, yPercent: 0.43),
        WarpPoint(warpID: "Route_213_Foot_Freak", xPercent: 0.64, yPercent: 0.85),
        WarpPoint(warpID: "Route_213_Door", xPercent: 0.71, yPercent: 0.22),
    ],
    "Route 221": [
        WarpPoint(warpID: "Route_221_House", xPercent: 0.29, yPercent: 0.54),
        WarpPoint(warpID: "Route_221_Pal_Park", xPercent: 0.79, yPercent: 0.43),
    ],
    "Survival Area": [
        WarpPoint(warpID: "Survival_Area_Centre_Entrance", xPercent: 0.57, yPercent: 0.66),
        WarpPoint(warpID: "Survival_Area_Mart_Entrance", xPercent: 0.68, yPercent: 0.66),
        WarpPoint(warpID: "Survival_Area_House", xPercent: 0.46, yPercent: 0.93),
        WarpPoint(warpID: "Survival_Area_Battleground", xPercent: 0.38, yPercent: 0.66),
        WarpPoint(warpID: "Survival_Area_Rock_House", xPercent: 0.49, yPercent: 0.22),
        WarpPoint(warpID: "Survival_Area_Centre_Exit", xPercent: 0.81, yPercent: 0.31),
        WarpPoint(warpID: "Survival_Area_Centre_Left", xPercent: 0.68, yPercent: 0.29),
        WarpPoint(warpID: "Survival_Area_Centre_Right", xPercent: 0.91, yPercent: 0.29),
    ],
    "Fuego Ironworks": [
        WarpPoint(warpID: "Fuego_Ironworks_Entrance", xPercent: 0.30, yPercent: 0.35),
        WarpPoint(warpID: "Fuego_Ironworks_Meadow_Entrance", xPercent: 0.66, yPercent: 0.75),
    ],
    "Route 209": [
        WarpPoint(warpID: "Route_209_Gate", xPercent: 0.11, yPercent: 0.51),
        WarpPoint(warpID: "Route_209_Tower", xPercent: 0.65, yPercent: 0.85),
    ],
    "Route 210": [
        WarpPoint(warpID: "Route_210_Milk", xPercent: 0.60, yPercent: 0.82),
        WarpPoint(warpID: "Route_210_House", xPercent: 0.55, yPercent: 0.27),
    ],
    "Route 215": [
        WarpPoint(warpID: "Route_215_Gate", xPercent: 0.72, yPercent: 0.68),
    ],
]
